# Hand made .travis.yml from pkg/travis.yml

dist: trusty

language: perl

perl:
- '5.26'
- '5.24'
- '5.22'
- '5.20'
- '5.18'
- '5.16'
- '5.14'

# XXX Failing these versions. DZ wants 5.14.
# - '5.12'
# - '5.10'
# - '5.8'

# before_install:
# - git clone git://github.com/travis-perl/helpers
#   ~/travis-perl-helpers
# - source ~/travis-perl-helpers/init --auto

install:
- perlbrew install-cpanm -f
- git clone https://github.com/ingydotnet/test-base-pm
    ../test-base-pm
# Travis Dist::Zilla was out of date on Jan 2, 2017
# Remove 'Dist::Zilla' after fixed.
- cpanm --quiet --notest
    Test::Base
    Zilla::Dist
    Dist::Zilla

script:
- zild disttest

notifications:
  irc:
    channels:
    - irc.perl.org#yaml
    on_success: change
    on_failure: always
    skip_join: true

# Hack to not run on tag pushes:
branches:
  except:
  - /^v?[0-9]+\.[0-9]+/
